version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/mongo:4
    environment:
      MONGO_URI: mongodb://localhost:27017/movieList
    working_directory: ~/movie-list
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          command: 'sudo npm install -g surge@latest apidoc@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: 'npm test -- --ci --forceExit'
      - run:
          name: Generate docs
          command: apidoc -i src/ -o docs/
      - run:
          name: Publish docs
          command: surge --project ~/movie-list/docs --domain https://movie-list-api.surge.sh
  deploy:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install heroku cli
          command: 'curl https://cli-assets.heroku.com/install.sh | sh'
      - run:
          name: Deploy to heroku
          command: |
            heroku container:login
            heroku container:push web -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build