version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/mongo:4
    environment:
      MONGO_URI=mongodb://localhost:27017/movieList
    working_directory: ~/movie-list
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: 'npm test -- --ci --forceExit'
